# Generated by Django 5.1.2 on 2024-10-20 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackRecord',
            fields=[
                ('tracker_id', models.CharField(default=uuid.UUID('44d7ac76-aa79-4b55-8702-d2413f081ac9'), max_length=60, primary_key=True, serialize=False)),
                ('email_recipient', models.CharField(max_length=250)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
