# Generated by Django 5.1.2 on 2024-10-21 02:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tracker', '0001_initial'), ('tracker', '0002_alter_trackrecord_tracker_id_visithistory'), ('tracker', '0003_trackrecord_visit_count_alter_trackrecord_tracker_id'), ('tracker', '0004_delete_visithistory')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackRecord',
            fields=[
                ('tracker_id', models.CharField(default=uuid.uuid4, max_length=60, primary_key=True, serialize=False)),
                ('email_recipient', models.CharField(max_length=250)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit_count', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
