# Generated by Django 5.1.2 on 2024-10-20 10:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackrecord',
            name='tracker_id',
            field=models.CharField(default=uuid.UUID('d93d88b2-4583-4d6b-a70a-8415b7cf9d3b'), max_length=60, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.PositiveSmallIntegerField(default=0)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.trackrecord')),
            ],
        ),
    ]
